apiVersion: catalog.cattle.io/v1
kind: UIPlugin
metadata:
  name: {{ .Chart.Name }}
  namespace: cattle-ui-plugin-system
spec:
  plugin: # should initially follow the design of the Helm Chart.yaml fields, could discuss modifying this
    name: {{ .Chart.Name }}
    version: {{ .Values.plugin.version }}
    endpoint: http://{{ .Chart.Name }}.cattle-ui-plugin-system.svc
    noCache: {{ .Values.plugin.noCache }}
