# Default values for sample.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
global:
  cattle:
    systemDefaultRegistry: ""
  kubectl:
    repository: rancher/kubectl
    tag: v1.20.2
    pullPolicy: IfNotPresent
image:
  repository: rancher/ui-plugin-server
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: "0.1.0"
imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
service:
  type: ClusterIP
  port: 80
  targetPort: 8080
pluginServer:
  replicas: 1
  resources: {}
  securityContext: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}
plugin:
  version: 0.0.1
  noCache: false

