name: E2E UI Plugin Server

on:
  workflow_dispatch:
    inputs:
      enable_tmate:
        description: 'Enable debugging via tmate'
        required: false
        default: "false"
  pull_request:
    paths-ignore:
      - 'docs/**'
      - 'scripts/**'
      - '*.md'
      - '*.dapper'
      - '.gitignore'
      - 'CODEOWNERS'
      - 'LICENSE'
      - 'Makefile'

env:
  GOARCH: amd64
  CGO_ENABLED: 0
  SETUP_GO_VERSION: '^1.18'

jobs:
  e2e-ui-plugin-server-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        k3s_version:
          # k3d version list k3s | sed 's/+/-/' | sort -h
          - v1.20.15-k3s1
    steps:
      -
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      -
        name: Build Docker Images
        run: REGISTRY= ORG=rancher REPO=ui-plugin-server TAG=dev ./scripts/package
      -
        name: Provision k3d Cluster
        uses: AbsaOSS/k3d-action@v2
        # k3d will automatically create a network named k3d-test-cluster-1 with the range 172.18.0.0/16
        with:
          cluster-name: "k3s-default"
          args: >-
            --agents 3
            --network "nw01"
            --image docker.io/rancher/k3s:${{matrix.k3s_version}}
      -
        name: Import Images Into k3d
        run: |
          k3d image import rancher/ui-plugin-server:dev
      -
        name: Set Up Tmate Debug Session
        if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.enable_tmate == 'true' }}
        uses: mxschmitt/action-tmate@v3
        timeout-minutes: 15
        with:
          limit-access-to-actor: true
      -
        name: Run helm install without UI Plugin CR using locally built k3d image
        run: |
          helm install --create-namespace -n cattle-ui-plugin-system ui-plugin-server --set pluginServer.image.tag=dev --set plugin.enabled=false ./charts/ui-plugin-server/;
          if ! kubectl -n cattle-ui-plugin-system rollout status deployment ui-plugin-server --timeout=10s; then kubectl get pods -n cattle-ui-plugin-system -o yaml; exit 1; fi
      -
        name: Start kubectl proxy and check if endpoint is up
        run: |
          kubectl proxy &
          sleep 2
          curl -sLf http://localhost:8001/api/v1/namespaces/cattle-ui-plugin-system/services/http:ui-plugin-server:80/proxy/files.txt
